### ISSUE TITLE
Blockchain transactions REST endpoint with 'hash' and 'since' parameters

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/sidetree-fabric#217]
Add a REST endpoint to retrieve Sidetree transactions from the blockchain since a given transaction time hash/number, according to: https://identity.foundation/sidetree/docs/swagger/#/Blockchain/getTransactions.

**Comment by troyronda** [comment]
The spec is a bit light on a couple details that we would desire (and we should support).

- we should also consider how to limit the response size so that we don’t overwhelm the server. (in a manner that meshes with the hash/since parameters).
- we should also consider another API endpoint for related block information (e.g., payload/signatures). e.g., /blockchain/blocks.
  - and how to link the the transactions to the blocks.

**Comment by troyronda** [comment]
Also noticed this API is using snake case for JSON properties, while the rest of the protocol switched to underscores. I’ll probably raise an issue in the sidetree spec repo to ask about that.
